// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: include/protos/state_field_registry.proto

// scao edited to be compat with platformio
#include <protos/state_field_registry.pb.h>

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Vector3f;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Vector4f;
}  // namespace protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto
class Vector3fDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Vector3f>
      _instance;
} _Vector3f_default_instance_;
class Vector4fDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Vector4f>
      _instance;
} _Vector4f_default_instance_;
class StateFieldRegistryDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StateFieldRegistry>
      _instance;
} _StateFieldRegistry_default_instance_;
namespace protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto {
static void InitDefaultsVector3f() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Vector3f_default_instance_;
    new (ptr) ::Vector3f();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Vector3f::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Vector3f =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsVector3f}, {}};

static void InitDefaultsVector4f() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Vector4f_default_instance_;
    new (ptr) ::Vector4f();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Vector4f::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Vector4f =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsVector4f}, {}};

static void InitDefaultsStateFieldRegistry() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_StateFieldRegistry_default_instance_;
    new (ptr) ::StateFieldRegistry();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::StateFieldRegistry::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_StateFieldRegistry =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsStateFieldRegistry}, {
      &protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::scc_info_Vector3f.base,
      &protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::scc_info_Vector4f.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Vector3f.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Vector4f.base);
  ::google::protobuf::internal::InitSCC(&scc_info_StateFieldRegistry.base);
}

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Vector3f, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Vector3f, elements_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Vector4f, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Vector4f, elements_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, time_t_average_cycle_time_us_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, time_t_control_cycle_limit_us_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, time_t_last_cycle_end_us_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, last_transition_ccno_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, mcl_control_cycle_num_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, mc_state_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, target_mc_state_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, gnc_state_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, target_gnc_state_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, imu_linear_acc_vec_f_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, imu_acc_vec_f_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, imu_gyr_vec_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, imu_euler_vec_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::StateFieldRegistry, imu_quat_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Vector3f)},
  { 6, -1, sizeof(::Vector4f)},
  { 12, -1, sizeof(::StateFieldRegistry)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_Vector3f_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_Vector4f_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_StateFieldRegistry_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "include/protos/state_field_registry.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n)include/protos/state_field_registry.pr"
      "oto\" \n\010Vector3f\022\024\n\010elements\030\001 \003(\002B\002\020\001\" \n"
      "\010Vector4f\022\024\n\010elements\030\001 \003(\002B\002\020\001\"\214\004\n\022Stat"
      "eFieldRegistry\022$\n\034time_t_average_cycle_t"
      "ime_us\030\001 \001(\002\022%\n\035time_t_control_cycle_lim"
      "it_us\030\002 \001(\005\022 \n\030time_t_last_cycle_end_us\030"
      "\003 \001(\r\022\034\n\024last_transition_ccno\030\004 \001(\004\022\035\n\025m"
      "cl_control_cycle_num\030\005 \001(\004\022#\n\010mc_state\030\006"
      " \001(\0162\021.MainControlState\022*\n\017target_mc_sta"
      "te\030\007 \001(\0162\021.MainControlState\022#\n\tgnc_state"
      "\030\010 \001(\0162\020.GncControlState\022*\n\020target_gnc_s"
      "tate\030\t \001(\0162\020.GncControlState\022\'\n\024imu_line"
      "ar_acc_vec_f\030\n \001(\0132\t.Vector3f\022 \n\rimu_acc"
      "_vec_f\030\013 \001(\0132\t.Vector3f\022\036\n\013imu_gyr_vec\030\014"
      " \001(\0132\t.Vector3f\022 \n\rimu_euler_vec\030\r \001(\0132\t"
      ".Vector4f\022\033\n\010imu_quat\030\016 \001(\0132\t.Vector4f* "
      "\n\020MainControlState\022\014\n\010MC_EMPTY\020\000* \n\017GncC"
      "ontrolState\022\r\n\tGNC_EMPTY\020\000b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 714);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "include/protos/state_field_registry.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto
const ::google::protobuf::EnumDescriptor* MainControlState_descriptor() {
  protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::file_level_enum_descriptors[0];
}
bool MainControlState_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* GncControlState_descriptor() {
  protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::file_level_enum_descriptors[1];
}
bool GncControlState_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void Vector3f::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Vector3f::kElementsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Vector3f::Vector3f()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::scc_info_Vector3f.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Vector3f)
}
Vector3f::Vector3f(const Vector3f& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      elements_(from.elements_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Vector3f)
}

void Vector3f::SharedCtor() {
}

Vector3f::~Vector3f() {
  // @@protoc_insertion_point(destructor:Vector3f)
  SharedDtor();
}

void Vector3f::SharedDtor() {
}

void Vector3f::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Vector3f::descriptor() {
  ::protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Vector3f& Vector3f::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::scc_info_Vector3f.base);
  return *internal_default_instance();
}


void Vector3f::Clear() {
// @@protoc_insertion_point(message_clear_start:Vector3f)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  elements_.Clear();
  _internal_metadata_.Clear();
}

bool Vector3f::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Vector3f)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float elements = 1 [packed = true];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_elements())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 10u, input, this->mutable_elements())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Vector3f)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Vector3f)
  return false;
#undef DO_
}

void Vector3f::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Vector3f)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float elements = 1 [packed = true];
  if (this->elements_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _elements_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->elements().data(), this->elements_size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Vector3f)
}

::google::protobuf::uint8* Vector3f::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Vector3f)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float elements = 1 [packed = true];
  if (this->elements_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _elements_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->elements_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Vector3f)
  return target;
}

size_t Vector3f::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Vector3f)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float elements = 1 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->elements_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _elements_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Vector3f::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Vector3f)
  GOOGLE_DCHECK_NE(&from, this);
  const Vector3f* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Vector3f>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Vector3f)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Vector3f)
    MergeFrom(*source);
  }
}

void Vector3f::MergeFrom(const Vector3f& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Vector3f)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  elements_.MergeFrom(from.elements_);
}

void Vector3f::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Vector3f)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Vector3f::CopyFrom(const Vector3f& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Vector3f)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Vector3f::IsInitialized() const {
  return true;
}

void Vector3f::Swap(Vector3f* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Vector3f::InternalSwap(Vector3f* other) {
  using std::swap;
  elements_.InternalSwap(&other->elements_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Vector3f::GetMetadata() const {
  protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Vector4f::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Vector4f::kElementsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Vector4f::Vector4f()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::scc_info_Vector4f.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Vector4f)
}
Vector4f::Vector4f(const Vector4f& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      elements_(from.elements_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Vector4f)
}

void Vector4f::SharedCtor() {
}

Vector4f::~Vector4f() {
  // @@protoc_insertion_point(destructor:Vector4f)
  SharedDtor();
}

void Vector4f::SharedDtor() {
}

void Vector4f::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Vector4f::descriptor() {
  ::protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Vector4f& Vector4f::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::scc_info_Vector4f.base);
  return *internal_default_instance();
}


void Vector4f::Clear() {
// @@protoc_insertion_point(message_clear_start:Vector4f)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  elements_.Clear();
  _internal_metadata_.Clear();
}

bool Vector4f::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Vector4f)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float elements = 1 [packed = true];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_elements())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 10u, input, this->mutable_elements())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Vector4f)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Vector4f)
  return false;
#undef DO_
}

void Vector4f::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Vector4f)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float elements = 1 [packed = true];
  if (this->elements_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _elements_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->elements().data(), this->elements_size(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Vector4f)
}

::google::protobuf::uint8* Vector4f::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Vector4f)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float elements = 1 [packed = true];
  if (this->elements_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _elements_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->elements_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Vector4f)
  return target;
}

size_t Vector4f::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Vector4f)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float elements = 1 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->elements_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _elements_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Vector4f::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Vector4f)
  GOOGLE_DCHECK_NE(&from, this);
  const Vector4f* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Vector4f>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Vector4f)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Vector4f)
    MergeFrom(*source);
  }
}

void Vector4f::MergeFrom(const Vector4f& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Vector4f)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  elements_.MergeFrom(from.elements_);
}

void Vector4f::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Vector4f)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Vector4f::CopyFrom(const Vector4f& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Vector4f)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Vector4f::IsInitialized() const {
  return true;
}

void Vector4f::Swap(Vector4f* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Vector4f::InternalSwap(Vector4f* other) {
  using std::swap;
  elements_.InternalSwap(&other->elements_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Vector4f::GetMetadata() const {
  protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void StateFieldRegistry::InitAsDefaultInstance() {
  ::_StateFieldRegistry_default_instance_._instance.get_mutable()->imu_linear_acc_vec_f_ = const_cast< ::Vector3f*>(
      ::Vector3f::internal_default_instance());
  ::_StateFieldRegistry_default_instance_._instance.get_mutable()->imu_acc_vec_f_ = const_cast< ::Vector3f*>(
      ::Vector3f::internal_default_instance());
  ::_StateFieldRegistry_default_instance_._instance.get_mutable()->imu_gyr_vec_ = const_cast< ::Vector3f*>(
      ::Vector3f::internal_default_instance());
  ::_StateFieldRegistry_default_instance_._instance.get_mutable()->imu_euler_vec_ = const_cast< ::Vector4f*>(
      ::Vector4f::internal_default_instance());
  ::_StateFieldRegistry_default_instance_._instance.get_mutable()->imu_quat_ = const_cast< ::Vector4f*>(
      ::Vector4f::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StateFieldRegistry::kTimeTAverageCycleTimeUsFieldNumber;
const int StateFieldRegistry::kTimeTControlCycleLimitUsFieldNumber;
const int StateFieldRegistry::kTimeTLastCycleEndUsFieldNumber;
const int StateFieldRegistry::kLastTransitionCcnoFieldNumber;
const int StateFieldRegistry::kMclControlCycleNumFieldNumber;
const int StateFieldRegistry::kMcStateFieldNumber;
const int StateFieldRegistry::kTargetMcStateFieldNumber;
const int StateFieldRegistry::kGncStateFieldNumber;
const int StateFieldRegistry::kTargetGncStateFieldNumber;
const int StateFieldRegistry::kImuLinearAccVecFFieldNumber;
const int StateFieldRegistry::kImuAccVecFFieldNumber;
const int StateFieldRegistry::kImuGyrVecFieldNumber;
const int StateFieldRegistry::kImuEulerVecFieldNumber;
const int StateFieldRegistry::kImuQuatFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StateFieldRegistry::StateFieldRegistry()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::scc_info_StateFieldRegistry.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:StateFieldRegistry)
}
StateFieldRegistry::StateFieldRegistry(const StateFieldRegistry& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_imu_linear_acc_vec_f()) {
    imu_linear_acc_vec_f_ = new ::Vector3f(*from.imu_linear_acc_vec_f_);
  } else {
    imu_linear_acc_vec_f_ = NULL;
  }
  if (from.has_imu_acc_vec_f()) {
    imu_acc_vec_f_ = new ::Vector3f(*from.imu_acc_vec_f_);
  } else {
    imu_acc_vec_f_ = NULL;
  }
  if (from.has_imu_gyr_vec()) {
    imu_gyr_vec_ = new ::Vector3f(*from.imu_gyr_vec_);
  } else {
    imu_gyr_vec_ = NULL;
  }
  if (from.has_imu_euler_vec()) {
    imu_euler_vec_ = new ::Vector4f(*from.imu_euler_vec_);
  } else {
    imu_euler_vec_ = NULL;
  }
  if (from.has_imu_quat()) {
    imu_quat_ = new ::Vector4f(*from.imu_quat_);
  } else {
    imu_quat_ = NULL;
  }
  ::memcpy(&time_t_average_cycle_time_us_, &from.time_t_average_cycle_time_us_,
    static_cast<size_t>(reinterpret_cast<char*>(&target_gnc_state_) -
    reinterpret_cast<char*>(&time_t_average_cycle_time_us_)) + sizeof(target_gnc_state_));
  // @@protoc_insertion_point(copy_constructor:StateFieldRegistry)
}

void StateFieldRegistry::SharedCtor() {
  ::memset(&imu_linear_acc_vec_f_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&target_gnc_state_) -
      reinterpret_cast<char*>(&imu_linear_acc_vec_f_)) + sizeof(target_gnc_state_));
}

StateFieldRegistry::~StateFieldRegistry() {
  // @@protoc_insertion_point(destructor:StateFieldRegistry)
  SharedDtor();
}

void StateFieldRegistry::SharedDtor() {
  if (this != internal_default_instance()) delete imu_linear_acc_vec_f_;
  if (this != internal_default_instance()) delete imu_acc_vec_f_;
  if (this != internal_default_instance()) delete imu_gyr_vec_;
  if (this != internal_default_instance()) delete imu_euler_vec_;
  if (this != internal_default_instance()) delete imu_quat_;
}

void StateFieldRegistry::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* StateFieldRegistry::descriptor() {
  ::protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StateFieldRegistry& StateFieldRegistry::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::scc_info_StateFieldRegistry.base);
  return *internal_default_instance();
}


void StateFieldRegistry::Clear() {
// @@protoc_insertion_point(message_clear_start:StateFieldRegistry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && imu_linear_acc_vec_f_ != NULL) {
    delete imu_linear_acc_vec_f_;
  }
  imu_linear_acc_vec_f_ = NULL;
  if (GetArenaNoVirtual() == NULL && imu_acc_vec_f_ != NULL) {
    delete imu_acc_vec_f_;
  }
  imu_acc_vec_f_ = NULL;
  if (GetArenaNoVirtual() == NULL && imu_gyr_vec_ != NULL) {
    delete imu_gyr_vec_;
  }
  imu_gyr_vec_ = NULL;
  if (GetArenaNoVirtual() == NULL && imu_euler_vec_ != NULL) {
    delete imu_euler_vec_;
  }
  imu_euler_vec_ = NULL;
  if (GetArenaNoVirtual() == NULL && imu_quat_ != NULL) {
    delete imu_quat_;
  }
  imu_quat_ = NULL;
  ::memset(&time_t_average_cycle_time_us_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&target_gnc_state_) -
      reinterpret_cast<char*>(&time_t_average_cycle_time_us_)) + sizeof(target_gnc_state_));
  _internal_metadata_.Clear();
}

bool StateFieldRegistry::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:StateFieldRegistry)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float time_t_average_cycle_time_us = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &time_t_average_cycle_time_us_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 time_t_control_cycle_limit_us = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &time_t_control_cycle_limit_us_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 time_t_last_cycle_end_us = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &time_t_last_cycle_end_us_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 last_transition_ccno = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &last_transition_ccno_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 mcl_control_cycle_num = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &mcl_control_cycle_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .MainControlState mc_state = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_mc_state(static_cast< ::MainControlState >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .MainControlState target_mc_state = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_target_mc_state(static_cast< ::MainControlState >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .GncControlState gnc_state = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_gnc_state(static_cast< ::GncControlState >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .GncControlState target_gnc_state = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_target_gnc_state(static_cast< ::GncControlState >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Vector3f imu_linear_acc_vec_f = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_imu_linear_acc_vec_f()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Vector3f imu_acc_vec_f = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_imu_acc_vec_f()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Vector3f imu_gyr_vec = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u /* 98 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_imu_gyr_vec()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Vector4f imu_euler_vec = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(106u /* 106 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_imu_euler_vec()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Vector4f imu_quat = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(114u /* 114 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_imu_quat()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:StateFieldRegistry)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:StateFieldRegistry)
  return false;
#undef DO_
}

void StateFieldRegistry::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:StateFieldRegistry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float time_t_average_cycle_time_us = 1;
  if (this->time_t_average_cycle_time_us() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->time_t_average_cycle_time_us(), output);
  }

  // int32 time_t_control_cycle_limit_us = 2;
  if (this->time_t_control_cycle_limit_us() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->time_t_control_cycle_limit_us(), output);
  }

  // uint32 time_t_last_cycle_end_us = 3;
  if (this->time_t_last_cycle_end_us() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->time_t_last_cycle_end_us(), output);
  }

  // uint64 last_transition_ccno = 4;
  if (this->last_transition_ccno() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(4, this->last_transition_ccno(), output);
  }

  // uint64 mcl_control_cycle_num = 5;
  if (this->mcl_control_cycle_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(5, this->mcl_control_cycle_num(), output);
  }

  // .MainControlState mc_state = 6;
  if (this->mc_state() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      6, this->mc_state(), output);
  }

  // .MainControlState target_mc_state = 7;
  if (this->target_mc_state() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      7, this->target_mc_state(), output);
  }

  // .GncControlState gnc_state = 8;
  if (this->gnc_state() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      8, this->gnc_state(), output);
  }

  // .GncControlState target_gnc_state = 9;
  if (this->target_gnc_state() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      9, this->target_gnc_state(), output);
  }

  // .Vector3f imu_linear_acc_vec_f = 10;
  if (this->has_imu_linear_acc_vec_f()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, this->_internal_imu_linear_acc_vec_f(), output);
  }

  // .Vector3f imu_acc_vec_f = 11;
  if (this->has_imu_acc_vec_f()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, this->_internal_imu_acc_vec_f(), output);
  }

  // .Vector3f imu_gyr_vec = 12;
  if (this->has_imu_gyr_vec()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, this->_internal_imu_gyr_vec(), output);
  }

  // .Vector4f imu_euler_vec = 13;
  if (this->has_imu_euler_vec()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      13, this->_internal_imu_euler_vec(), output);
  }

  // .Vector4f imu_quat = 14;
  if (this->has_imu_quat()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      14, this->_internal_imu_quat(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:StateFieldRegistry)
}

::google::protobuf::uint8* StateFieldRegistry::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:StateFieldRegistry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float time_t_average_cycle_time_us = 1;
  if (this->time_t_average_cycle_time_us() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->time_t_average_cycle_time_us(), target);
  }

  // int32 time_t_control_cycle_limit_us = 2;
  if (this->time_t_control_cycle_limit_us() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->time_t_control_cycle_limit_us(), target);
  }

  // uint32 time_t_last_cycle_end_us = 3;
  if (this->time_t_last_cycle_end_us() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->time_t_last_cycle_end_us(), target);
  }

  // uint64 last_transition_ccno = 4;
  if (this->last_transition_ccno() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(4, this->last_transition_ccno(), target);
  }

  // uint64 mcl_control_cycle_num = 5;
  if (this->mcl_control_cycle_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(5, this->mcl_control_cycle_num(), target);
  }

  // .MainControlState mc_state = 6;
  if (this->mc_state() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      6, this->mc_state(), target);
  }

  // .MainControlState target_mc_state = 7;
  if (this->target_mc_state() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      7, this->target_mc_state(), target);
  }

  // .GncControlState gnc_state = 8;
  if (this->gnc_state() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      8, this->gnc_state(), target);
  }

  // .GncControlState target_gnc_state = 9;
  if (this->target_gnc_state() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      9, this->target_gnc_state(), target);
  }

  // .Vector3f imu_linear_acc_vec_f = 10;
  if (this->has_imu_linear_acc_vec_f()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        10, this->_internal_imu_linear_acc_vec_f(), deterministic, target);
  }

  // .Vector3f imu_acc_vec_f = 11;
  if (this->has_imu_acc_vec_f()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        11, this->_internal_imu_acc_vec_f(), deterministic, target);
  }

  // .Vector3f imu_gyr_vec = 12;
  if (this->has_imu_gyr_vec()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        12, this->_internal_imu_gyr_vec(), deterministic, target);
  }

  // .Vector4f imu_euler_vec = 13;
  if (this->has_imu_euler_vec()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        13, this->_internal_imu_euler_vec(), deterministic, target);
  }

  // .Vector4f imu_quat = 14;
  if (this->has_imu_quat()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        14, this->_internal_imu_quat(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:StateFieldRegistry)
  return target;
}

size_t StateFieldRegistry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:StateFieldRegistry)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .Vector3f imu_linear_acc_vec_f = 10;
  if (this->has_imu_linear_acc_vec_f()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *imu_linear_acc_vec_f_);
  }

  // .Vector3f imu_acc_vec_f = 11;
  if (this->has_imu_acc_vec_f()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *imu_acc_vec_f_);
  }

  // .Vector3f imu_gyr_vec = 12;
  if (this->has_imu_gyr_vec()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *imu_gyr_vec_);
  }

  // .Vector4f imu_euler_vec = 13;
  if (this->has_imu_euler_vec()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *imu_euler_vec_);
  }

  // .Vector4f imu_quat = 14;
  if (this->has_imu_quat()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *imu_quat_);
  }

  // float time_t_average_cycle_time_us = 1;
  if (this->time_t_average_cycle_time_us() != 0) {
    total_size += 1 + 4;
  }

  // int32 time_t_control_cycle_limit_us = 2;
  if (this->time_t_control_cycle_limit_us() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->time_t_control_cycle_limit_us());
  }

  // uint64 last_transition_ccno = 4;
  if (this->last_transition_ccno() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->last_transition_ccno());
  }

  // uint32 time_t_last_cycle_end_us = 3;
  if (this->time_t_last_cycle_end_us() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->time_t_last_cycle_end_us());
  }

  // .MainControlState mc_state = 6;
  if (this->mc_state() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->mc_state());
  }

  // uint64 mcl_control_cycle_num = 5;
  if (this->mcl_control_cycle_num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->mcl_control_cycle_num());
  }

  // .MainControlState target_mc_state = 7;
  if (this->target_mc_state() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->target_mc_state());
  }

  // .GncControlState gnc_state = 8;
  if (this->gnc_state() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->gnc_state());
  }

  // .GncControlState target_gnc_state = 9;
  if (this->target_gnc_state() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->target_gnc_state());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StateFieldRegistry::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:StateFieldRegistry)
  GOOGLE_DCHECK_NE(&from, this);
  const StateFieldRegistry* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StateFieldRegistry>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:StateFieldRegistry)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:StateFieldRegistry)
    MergeFrom(*source);
  }
}

void StateFieldRegistry::MergeFrom(const StateFieldRegistry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:StateFieldRegistry)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_imu_linear_acc_vec_f()) {
    mutable_imu_linear_acc_vec_f()->::Vector3f::MergeFrom(from.imu_linear_acc_vec_f());
  }
  if (from.has_imu_acc_vec_f()) {
    mutable_imu_acc_vec_f()->::Vector3f::MergeFrom(from.imu_acc_vec_f());
  }
  if (from.has_imu_gyr_vec()) {
    mutable_imu_gyr_vec()->::Vector3f::MergeFrom(from.imu_gyr_vec());
  }
  if (from.has_imu_euler_vec()) {
    mutable_imu_euler_vec()->::Vector4f::MergeFrom(from.imu_euler_vec());
  }
  if (from.has_imu_quat()) {
    mutable_imu_quat()->::Vector4f::MergeFrom(from.imu_quat());
  }
  if (from.time_t_average_cycle_time_us() != 0) {
    set_time_t_average_cycle_time_us(from.time_t_average_cycle_time_us());
  }
  if (from.time_t_control_cycle_limit_us() != 0) {
    set_time_t_control_cycle_limit_us(from.time_t_control_cycle_limit_us());
  }
  if (from.last_transition_ccno() != 0) {
    set_last_transition_ccno(from.last_transition_ccno());
  }
  if (from.time_t_last_cycle_end_us() != 0) {
    set_time_t_last_cycle_end_us(from.time_t_last_cycle_end_us());
  }
  if (from.mc_state() != 0) {
    set_mc_state(from.mc_state());
  }
  if (from.mcl_control_cycle_num() != 0) {
    set_mcl_control_cycle_num(from.mcl_control_cycle_num());
  }
  if (from.target_mc_state() != 0) {
    set_target_mc_state(from.target_mc_state());
  }
  if (from.gnc_state() != 0) {
    set_gnc_state(from.gnc_state());
  }
  if (from.target_gnc_state() != 0) {
    set_target_gnc_state(from.target_gnc_state());
  }
}

void StateFieldRegistry::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:StateFieldRegistry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StateFieldRegistry::CopyFrom(const StateFieldRegistry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:StateFieldRegistry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StateFieldRegistry::IsInitialized() const {
  return true;
}

void StateFieldRegistry::Swap(StateFieldRegistry* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StateFieldRegistry::InternalSwap(StateFieldRegistry* other) {
  using std::swap;
  swap(imu_linear_acc_vec_f_, other->imu_linear_acc_vec_f_);
  swap(imu_acc_vec_f_, other->imu_acc_vec_f_);
  swap(imu_gyr_vec_, other->imu_gyr_vec_);
  swap(imu_euler_vec_, other->imu_euler_vec_);
  swap(imu_quat_, other->imu_quat_);
  swap(time_t_average_cycle_time_us_, other->time_t_average_cycle_time_us_);
  swap(time_t_control_cycle_limit_us_, other->time_t_control_cycle_limit_us_);
  swap(last_transition_ccno_, other->last_transition_ccno_);
  swap(time_t_last_cycle_end_us_, other->time_t_last_cycle_end_us_);
  swap(mc_state_, other->mc_state_);
  swap(mcl_control_cycle_num_, other->mcl_control_cycle_num_);
  swap(target_mc_state_, other->target_mc_state_);
  swap(gnc_state_, other->gnc_state_);
  swap(target_gnc_state_, other->target_gnc_state_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata StateFieldRegistry::GetMetadata() const {
  protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_include_2fprotos_2fstate_5ffield_5fregistry_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Vector3f* Arena::CreateMaybeMessage< ::Vector3f >(Arena* arena) {
  return Arena::CreateInternal< ::Vector3f >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Vector4f* Arena::CreateMaybeMessage< ::Vector4f >(Arena* arena) {
  return Arena::CreateInternal< ::Vector4f >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::StateFieldRegistry* Arena::CreateMaybeMessage< ::StateFieldRegistry >(Arena* arena) {
  return Arena::CreateInternal< ::StateFieldRegistry >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
