/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "include/nanopb/state_field_registry.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Vector3f, Vector3f, AUTO)


PB_BIND(Vector4f, Vector4f, AUTO)


PB_BIND(StateFieldRegistry, StateFieldRegistry, AUTO)





